### Indexación

In [4]:
x <- 1:30

In [5]:
x[8:12]

[1]  8  9 10 11 12

In [7]:
y <- matrix(1:9, 3, 3)
y

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [8]:
y[1:2, 3]

[1] 7 8

In [9]:
z <- array(1:27, c(3,3,3)) # un arreglo
z

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27

In [11]:
#      f   c  h   -> f:fila, c:columna, h:hoja
z[2:3, 2, 3]

[1] 23 24

In [15]:
z[1,c(1,3),2]

[1] 10 16

In [17]:
z[,,2] # todas las filas y columnas de la hoja 2

[,1] [,2] [,3]
[1,] 10   13   16  
[2,] 11   14   17  
[3,] 12   15   18

In [ ]:
[c(-2), 1, 1]

### Extracción

In [28]:
x <- seq(1, 39)
x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39

In [33]:

cat <- sample(c("a", "b"), 20, replace = T)
cat
x

# obtener los elementos en x mayores a 15 y menores a 27
x[x>15 & x<27]


[1] "a" "b" "a" "b" "a" "b" "a" "a" "a" "a" "b" "a" "b" "a" "a" "b" "b" "b" "a"
[20] "b"

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39

[1] 16 17 18 19 20 21 22 23 24 25 26

In [ ]:
Ejercicios

In [47]:
# 1 Genere un vector con 100 números aleatorios entre 1 y 800. Use la función sample
numeros <- sample(1:800,100,replace=F) 


In [38]:
# 2 Gener un vecotr con 4 nivles: "a", "b", "c", "d". Use la función rep
letras <- rep(c("a", "b", "c", "d"), 25)

In [44]:
# 3 Una estos dos vectores en un dataframe. Use la función 
df <- data.frame(numeros, letras)




In [45]:
#4 Estraer los elementos 10, 15, 20, 25
numeros[c(10, 15, 20, 25)]

[1] 539 335 622  35

In [46]:
#5
numeros[numeros > 500]

[1] 784 539 570 596 662 515 743 622 731 631 525 686 716 706 601 721 531 612 529
[20] 649 540 690 532 592 572 723 604 685 726 714 590 633 707 759 732 798 656 781
[39] 769 677 593 600 514 796 719 681

In [49]:
df

numeros letras
1   784     a     
2   386     b     
3   367     c     
4   137     d     
5   415     a     
6    23     b     
7   410     c     
8   256     d     
9    95     a     
10  539     b     
11  570     c     
12  596     d     
13    4     a     
14  662     b     
15  335     c     
16   38     d     
17    1     a     
18  515     b     
19  743     c     
20  622     d     
21   91     a     
22   25     b     
23  437     c     
24  731     d     
25   35     a     
26  631     b     
27  496     c     
28  525     d     
29  686     a     
30  716     b     
... ...     ...   
71  230     c     
72  372     d     
73  759     a     
74  732     b     
75  798     c     
76  469     d     
77  656     a     
78  492     b     
79  299     c     
80  110     d     
81  248     a     
82  145     b     
83  358     c     
84  168     d     
85  781     a     
86  769     b     
87  677     c     
88  593     d     
89  292     a     
90  497     b     
91  600     c     
92   54     d     
93  189     a     
94  483     b     
95  514     c     
96   39     d     
97  796     a     
98  719     b     
99   84     c     
100 681     d

In [60]:
#6 Con el data.frame creado en punto 3. Obtenga todas las columnas con las filas que son igual a "b" y "c"
df[df$letras == c("c", "b"), ]

numeros letras
2  386     b     
3  367     c     
6   23     b     
7  410     c     
10 539     b     
11 570     c     
14 662     b     
15 335     c     
18 515     b     
19 743     c     
22  25     b     
23 437     c     
26 631     b     
27 496     c     
30 716     b     
31 143     c     
34 601     b     
35 721     c     
38 121     b     
39 531     c     
42 529     b     
43 649     c     
46 540     b     
47 690     c     
50 592     b     
51 457     c     
54  20     b     
55 572     c     
58 180     b     
59 685     c     
62 714     b     
63  90     c     
66 365     b     
67 633     c     
70  53     b     
71 230     c     
74 732     b     
75 798     c     
78 492     b     
79 299     c     
82 145     b     
83 358     c     
86 769     b     
87 677     c     
90 497     b     
91 600     c     
94 483     b     
95 514     c     
98 719     b     
99  84     c

In [63]:
#7 En el vector caracter de niveles extraiga los datos que son mayores a "b"
letras[letras > "b"]

[1] "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c"
[20] "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d"
[39] "c" "d" "c" "d" "c" "d" "c" "d" "c" "d" "c" "d"

In [64]:
# 8 Elimine de la matriz los casos(filas) que son iguales a "d"
df <- df[df$letras != ("d"), ]

numeros letras
1   784     a     
2   386     b     
3   367     c     
5   415     a     
6    23     b     
7   410     c     
9    95     a     
10  539     b     
11  570     c     
13    4     a     
14  662     b     
15  335     c     
17    1     a     
18  515     b     
19  743     c     
21   91     a     
22   25     b     
23  437     c     
25   35     a     
26  631     b     
27  496     c     
29  686     a     
30  716     b     
31  143     c     
33  337     a     
34  601     b     
35  721     c     
37   48     a     
38  121     b     
39  531     c     
... ...     ...   
61  422     a     
62  714     b     
63   90     c     
65  590     a     
66  365     b     
67  633     c     
69   55     a     
70   53     b     
71  230     c     
73  759     a     
74  732     b     
75  798     c     
77  656     a     
78  492     b     
79  299     c     
81  248     a     
82  145     b     
83  358     c     
85  781     a     
86  769     b     
87  677     c     
89  292     a     
90  497     b     
91  600     c     
93  189     a     
94  483     b     
95  514     c     
97  796     a     
98  719     b     
99   84     c